import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
import { pg_trgm } from '@electric-sql/pglite/contrib/pg_trgm';
import { createDraft, toHistoryRecord } from '../src/services/InvoiceService';
import { defaultSettings } from '../src/models/BusinessSettings';
import { StorageService } from '../src/services/StorageService';
import { LocalCustomerRepository } from '../src/repositories/WorkspaceRepositories';
import { LocalInvoiceRepository } from '../src/repositories/LocalInvoiceRepository';
import { importLocalData, inspectLocalData } from '../src/services/GuestMigrationService';
import { buildInvoiceHtml } from '../src/services/pdf/invoiceHtml';

const maruti = 'c8a94e21-5162-4d77-b436-819362b86ac0';
const a = '11111111-1111-4111-8111-111111111111', b = '22222222-2222-4222-8222-222222222222';
const c = '33333333-3333-4333-8333-333333333333', d = '44444444-4444-4444-8444-444444444444';
test('workspace migration preserves rows, verified allowlist, RLS isolation, private assets and atomic invoice writes', async () => {
 const db = await PGlite.create({ extensions: { pgcrypto, pg_trgm } });
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
   create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
   create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;
   grant usage on schema auth to anon,authenticated; grant execute on all functions in schema auth to anon,authenticated;
   create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
   alter table storage.objects enable row level security; grant usage on schema storage to anon,authenticated;
   grant all on storage.objects to anon,authenticated;`);
  for (const filename of ['202609120001_customers.sql', '202609120002_production_schema.sql']) await db.exec(await readFile(`supabase/migrations/${filename}`, 'utf8'));
  await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,'pathmgandhi@gmail.com',now(),'{\"full_name\":\"First owner\"}'),($2,'MANISH10GANDHI@gmail.com',null,'{}'),($3,'generic-a@example.test',now(),'{\"email\":\"pathmgandhi@gmail.com\",\"role\":\"owner\"}'),($4,'generic-b@example.test',now(),'{}')", [a,b,c,d]);
  const legacy = (await db.query<{id:string}>("insert into customers(owner_id,username,full_name) values($1,'shared','Preserved original') returning id",[a])).rows[0]!.id;
  const migration = await readFile('supabase/migrations/202609120003_auth_workspaces.sql','utf8');
  await db.exec(migration); await db.exec(migration);
  assert.equal((await db.query('select id from customers where id=$1 and business_id=$2',[legacy,maruti])).rows.length,1);
  const login = async (id:string) => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,role:'authenticated',email:'pathmgandhi@gmail.com'})]); await db.exec('set role authenticated'); };
  await db.exec('set role anon');
  for (const table of ['customers','profiles','businesses','business_members','business_access_allowlist','invoices','invoice_items','business_settings']) await assert.rejects(db.query(`select * from ${table}`),/permission denied/);
  await assert.rejects(db.query('select * from ensure_workspace()'),/permission denied/);
  assert.equal((await db.query("select * from storage.objects where bucket_id='business-assets'")).rows.length,0);
  await login(a);
  assert.equal((await db.query('select * from ensure_workspace()')).rows.length,1);
  assert.equal((await db.query('select * from profiles')).rows.length,1);
  assert.equal((await db.query('select * from customers')).rows.length,1);
  await db.exec("update profiles set full_name='Edited owner'");
  await db.query("insert into storage.objects(bucket_id,name) values('business-assets',$1)",[`${maruti}/logo/private.png`]);
  await db.query("insert into workspace_user_state values($1,$2,'draft','{}',now())",[maruti,a]);
  await login(b); // allowlisted but unverified email has no shared access
  assert.equal((await db.query('select * from customers')).rows.length,0);
  await assert.rejects(db.query('select * from search_business_customers($1,\'sh\',15)',[maruti]),/Workspace access/);
  await db.exec('reset role'); await db.query('update auth.users set email_confirmed_at=now() where id=$1',[b]);
  await login(b);
  assert.equal((await db.query('select * from customers')).rows.length,1);
  assert.equal((await db.query('select * from workspace_user_state')).rows.length,0);
  assert.equal((await db.query('select * from storage.objects')).rows.length,1);
  await db.exec("update customers set full_name='Edited by second member'");
  const invoice = {...createDraft(defaultSettings),customerId:legacy,customerName:'Snapshot customer',planName:'Plan',timePeriod:'12 months',price:1000,discount:10,installationCharges:200};
  const saved = (await db.query<{id:string}>('select save_invoice_document($1,$2) as id',[maruti,JSON.stringify(invoice)])).rows[0]!.id;
  assert.equal((await db.query<{total_amount:string}>('select total_amount from invoices')).rows[0]?.total_amount,'1100.00');
  assert.equal((await db.query<{line_total:string}>('select line_total from invoice_items')).rows[0]?.line_total,'900.00');
  await assert.rejects(db.query('select save_invoice_document($1,$2)',[maruti,JSON.stringify({...invoice,price:-1})]),/Invalid invoice amounts/);
  assert.equal((await db.query('select * from invoice_items')).rows.length,1);
  await assert.rejects(db.query('delete from invoices'),/permission denied/);
  await login(a);
  await db.query('select save_invoice_document($1,$2)',[maruti,JSON.stringify({...invoice,isPaid:true})]);
  assert.equal((await db.query('select id from invoices where id=$1 and is_paid',[saved])).rows.length,1);
  await login(c);
  const own = (await db.query<{id:string}>('select * from ensure_workspace()')).rows[0]!.id;
  assert.notEqual(own,maruti);
  for (const table of ['customers','invoices','invoice_items','business_settings','workspace_user_state']) assert.equal((await db.query(`select * from ${table}`)).rows.length,0);
  assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await assert.rejects(db.query('select save_invoice_document($1,$2)',[maruti,JSON.stringify(invoice)]),/Workspace access/);
  await assert.rejects(db.query('select save_invoice_document($1,$2)',[own,JSON.stringify(invoice)]),/Customer does not belong/);
  await assert.rejects(db.query('insert into business_members(business_id,user_id) values($1,$2)',[maruti,c]),/permission denied/);
  await assert.rejects(db.query('select * from business_access_allowlist'),/permission denied/);
  await assert.rejects(db.query('select gigainvoice_provision_user($1)',[a]),/permission denied/);
  await assert.rejects(db.query("insert into customers(business_id,username,full_name) values($1,'intruder','No')",[maruti]),/row-level security/);
  await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('business-assets',$1)",[`${maruti}/logo/stolen.png`]),/row-level security/);
  await db.query("insert into customers(business_id,owner_id,username,full_name) values($1,$2,'personal','Personal customer')",[own,c]);
  await db.query('insert into business_settings(business_id,owner_id) values($1,$2)',[own,c]);
  assert.equal((await db.query<{company_name:null}>('select company_name from business_settings')).rows[0]?.company_name,null);
  await login(d); assert.equal((await db.query('select * from customers')).rows.length,0);
  await db.exec('reset role');
  await db.query('insert into business_members(business_id,user_id) values($1,$2)',[maruti,c]);
  await login(c); assert.equal((await db.query('select * from customers where business_id=$1',[maruti])).rows.length,0);
  await db.exec('reset role'); await db.query("update auth.users set email='changed@example.test' where id=$1",[a]);
  await login(a); assert.equal((await db.query('select * from customers')).rows.length,0); // old email JWT cannot grant access
  await db.exec('reset role'); await db.query('delete from auth.users where id=$1',[a]);
  assert.equal((await db.query('select id from customers where id=$1',[legacy])).rows.length,1);
  await login(b); assert.equal((await db.query('select * from customers')).rows.length,1);
 } finally { await db.close(); }
});

test('guest isolation, explicit protected import, retries and blank branding', async () => {
 const values = new Map<string,string>();
 const adapter = { getItem: async (key:string) => values.get(key)??null, setItem: async (key:string,value:string) => {values.set(key,value);} };
 const legacy = new StorageService(adapter), guest = new StorageService(adapter,'gigainvoice:v2:guest:');
 const journal = new StorageService(adapter,'prefs:');
 await legacy.set('customers',[{username:'private',full_name:'Protected legacy'}]);
 const guestCustomers = new LocalCustomerRepository(guest);
 assert.equal(await guestCustomers.count(),0);
 await guestCustomers.save({username:'local',full_name:'Local customer'});
 const invoice = toHistoryRecord({...createDraft(defaultSettings),customerName:'Local customer',planName:'Plan',timePeriod:'12 months'});
 await new LocalInvoiceRepository(guest).save(invoice);
 const data = await inspectLocalData(guest);
 let customerSaves=0, invoiceSaves=0, failed=true;
 const target = { customers: {count:async()=>0,search:async()=>[],getAll:async()=>[],save:async()=>{customerSaves++;}}, invoices: { getAll:async()=>[],search:async()=>[],save:async()=>{if(failed){failed=false;throw new Error('Network interrupted');}invoiceSaves++;}}, saveSettings:async()=>{},openInvoice:async()=>{} };
 const options = {customers:true,settings:false,draft:false,protectedBusiness:true,confirmMaster:false};
 assert.equal(customerSaves,0);
 await assert.rejects(importLocalData(data,target,options,journal,'a'),/Confirm/);
 await assert.rejects(importLocalData(data,target,{...options,confirmMaster:true},journal,'a'),/Network/);
 await importLocalData(data,target,{...options,confirmMaster:true},journal,'a');
 await importLocalData(data,target,{...options,confirmMaster:true},journal,'a');
 assert.equal(customerSaves,1); assert.equal(invoiceSaves,1);
 assert.equal((await inspectLocalData(guest)).invoices.length,1);
 const html = buildInvoiceHtml(invoice.data);
 assert.ok(!html.includes('<img class="gi-logo"')); assert.ok(!html.includes('Maruti')); assert.ok(!html.includes('Ajay'));
 assert.equal(defaultSettings.companyName,''); assert.equal(defaultSettings.upiId,''); assert.equal(defaultSettings.logo,null);
});
