import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

async function main() {
  await mkdir('assets', { recursive: true });
  await mkdir('src/data', { recursive: true });
  const symbol = `<g fill="none" stroke="white" stroke-width="36" stroke-linecap="round"><path d="M292 437 Q512 230 732 437"/><path d="M370 517 Q512 381 654 517"/><path d="M448 596 Q512 532 576 596"/></g><circle cx="512" cy="678" r="27" fill="white"/>`;
  const svg = (background: boolean) => Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><defs><linearGradient id="b" x2="1" y2="1"><stop stop-color="#2563eb"/><stop offset="1" stop-color="#6d28d9"/></linearGradient></defs>${background ? '<rect width="1024" height="1024" rx="216" fill="url(#b)"/>' : ''}${symbol}</svg>`);
  await sharp(svg(true)).png().toFile('assets/icon.png');
  await sharp(svg(false)).png().toFile('assets/adaptive-icon.png');
  await sharp(svg(true)).resize(256).png().toFile('assets/splash-icon.png');
  await sharp(svg(true)).resize(64).png().toFile('assets/favicon.png');
  const regular = await readFile(path.join('node_modules', '@expo-google-fonts/inter/400Regular/Inter_400Regular.ttf'));
  const bold = await readFile(path.join('node_modules', '@expo-google-fonts/inter/600SemiBold/Inter_600SemiBold.ttf'));
  await writeFile('src/data/printAssets.ts', `// Generated by npm run prepare:assets. Fonts only; no business identity.\nexport const printAssets = ${JSON.stringify({ regular: regular.toString('base64'), bold: bold.toString('base64') })} as const;\n`);
  console.info('App icons, splash image, and offline PDF assets prepared.');
}
main().catch(error => { console.error(error.message); process.exitCode = 1; });
