// Database contract for the production migration.
export type CustomerRow = {
  business_id: string | null;
  id: string;
  owner_id: string | null;
  username: string;
  full_name: string;
  email: string | null;
  phone: string | null;
  address: string | null;
  package: string | null;
  expiry_date: string | null;
  last_recharge_date: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};
export type BusinessSettingsRow = {
  business_id: string | null;
  id: string;
  owner_id: string | null;
  company_name: string | null;
  address1: string | null;
  address2: string | null;
  address3: string | null;
  country: string | null;
  phone: string | null;
  email: string | null;
  upi_id: string | null;
  currency_symbol: string;
  default_plan_name: string | null;
  default_time_period: string | null;
  default_installation_charge: number;
  accent_color: string;
  logo_path: string | null;
  show_qr: boolean;
  created_at: string;
  updated_at: string;
};
export type InvoiceRow = {
  business_id: string | null;
  local_id: string | null;
  document: Json | null;
  id: string;
  owner_id: string | null;
  customer_id: string | null;
  invoice_number: string;
  document_type: 'invoice' | 'receipt';
  status: 'draft' | 'issued' | 'paid' | 'cancelled';
  start_date: string | null;
  due_date: string | null;
  payment_date: string | null;
  customer_username: string | null;
  customer_name: string;
  customer_phone: string | null;
  customer_email: string | null;
  customer_address: string | null;
  customer_package: string | null;
  customer_expiry_date: string | null;
  customer_last_recharge_date: string | null;
  currency_symbol: string;
  subtotal: number;
  discount_percent: number;
  discount_amount: number;
  installation_charges: number;
  total_amount: number;
  is_paid: boolean;
  payment_method: string | null;
  paid_at: string | null;
  show_qr: boolean;
  qr_type: 'upi' | 'custom';
  upi_id: string | null;
  custom_qr_path: string | null;
  accent_color: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};
export type InvoiceItemRow = {
  business_id: string | null;
  id: string;
  invoice_id: string;
  owner_id: string | null;
  plan_name: string;
  description: string | null;
  time_period: string | null;
  quantity: number;
  unit_price: number;
  discount_percent: number;
  line_total: number;
  sort_order: number;
  created_at: string;
};
type Table<Row, Required extends keyof Row> = { Row: Row; Insert: Pick<Row, Required> & Partial<Row>; Update: Partial<Row>; Relationships: [] };
export type Json = string | number | boolean | null | Json[] | { [key: string]: Json | undefined };
export type ProfileRow = { id: string; full_name: string | null; phone: string | null; avatar_path: string | null; created_at: string; updated_at: string };
export type BusinessRow = { id: string; name: string | null; protected_key: string | null; created_at: string; updated_at: string };
export type MemberRow = { id: string; business_id: string; user_id: string; role: string; status: string; created_at: string };
export type UserStateRow = { business_id: string; user_id: string; key: string; value: Json; updated_at: string };
export interface Database {
  public: {
    Tables: {
      profiles: Table<ProfileRow, 'id'>;
      businesses: Table<BusinessRow, never>;
      business_members: Table<MemberRow, 'business_id' | 'user_id'>;
      workspace_user_state: Table<UserStateRow, 'business_id' | 'user_id' | 'key' | 'value'>;
      customers: Table<CustomerRow, 'username' | 'full_name'>;
      business_settings: Table<BusinessSettingsRow, 'owner_id'>;
      invoices: Table<InvoiceRow, 'owner_id' | 'invoice_number' | 'customer_name'>;
      invoice_items: Table<InvoiceItemRow, 'invoice_id' | 'owner_id' | 'plan_name'>;
    };
    Views: Record<string, never>;
    Functions: {
      search_customers: { Args: { search_text: string; result_limit: number }; Returns: CustomerRow[] };
      search_business_customers: { Args: { target_business_id: string; search_text: string; result_limit: number }; Returns: CustomerRow[] };
      ensure_workspace: { Args: Record<string, never>; Returns: BusinessRow[] };
      save_invoice_document: { Args: { target_business_id: string; payload: Json }; Returns: string };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
